%YAML:1.0

#--------------------------------------------------------------------------------------------
# Drawer Params: the extra params of trajectory_drawer class
# Params Guide https://slampy.readthedocs.io/en/latest/config.html
#--------------------------------------------------------------------------------------------

Drawer.eye.x: -18.0
Drawer.eye.y: -13.0
Drawer.eye.z: -55.0
Drawer.center.x: -17.0
Drawer.center.y: -8.0
Drawer.scale_grade.x: 1.0
Drawer.scale_grade.y: 1.0
Drawer.scale_grade.z: 10.0
Drawer.aspectratio.x: 50
Drawer.aspectratio.y: 50
Drawer.aspectratio.z: 100
Drawer.point_size: 2
